# Generated by Django 3.1.7 on 2023-04-05 10:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_mon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('name', models.CharField(max_length=100, null=True)),
                ('surname', models.CharField(max_length=100, null=True)),
                ('login', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('password', models.CharField(max_length=200, null=True)),
                ('date_reg', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('access', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('balance', models.PositiveBigIntegerField(default=0, null=True)),
                ('avail_balance', models.PositiveBigIntegerField(default=0, null=True, validators=[django.core.validators.MaxValueValidator(30000)])),
                ('region', models.CharField(choices=[('Чуйская', 'Чуйская'), ('Иссык-кульская', 'Иссык-кульская'), ('Нарынская', 'Нарынская'), ('Джалал-Абадская', 'Джалал-Абадская'), ('Баткенская', 'Баткенская'), ('Ошская', 'Ошская'), ('Таласская', 'Таласская')], max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pays',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_payment', models.CharField(max_length=100, null=True)),
                ('date_payment', models.CharField(max_length=100, null=True, verbose_name='Дата')),
                ('accept_payment', models.CharField(max_length=100, null=True)),
                ('ls_abon', models.CharField(max_length=100, null=True)),
                ('money', models.CharField(max_length=30, null=True)),
                ('status_payment', models.CharField(max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_id', to='localpay.user_mon', verbose_name='Монтажники')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='localpay.user_mon')),
            ],
        ),
    ]
