# Generated by Django 3.1.7 on 2023-04-06 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('localpay', '0002_app1admingroup'),
    ]

    operations = [
        migrations.DeleteModel(
            name='App1AdminGroup',
        ),
    ]
