# Generated by Django 3.1.7 on 2023-04-06 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localpay', '0003_delete_app1admingroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_mon',
            name='avail_balance',
            field=models.BigIntegerField(default=0, null=True),
        ),
    ]
