# Generated by Django 3.1.7 on 2023-04-10 02:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('localpay', '0004_auto_20230406_1659'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pays',
            options={'verbose_name': 'История  платежа', 'verbose_name_plural': 'История  платежей'},
        ),
        migrations.AlterModelOptions(
            name='user_mon',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterField(
            model_name='pays',
            name='ls_abon',
            field=models.CharField(max_length=100, null=True, verbose_name='Лицевой счет'),
        ),
        migrations.AlterField(
            model_name='pays',
            name='money',
            field=models.CharField(max_length=30, null=True, verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='pays',
            name='status_payment',
            field=models.CharField(max_length=100, null=True, verbose_name='Статус  оплаты'),
        ),
        migrations.AlterField(
            model_name='pays',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_id', to=settings.AUTH_USER_MODEL, verbose_name='Монтажник'),
        ),
        migrations.AlterField(
            model_name='user_mon',
            name='access',
            field=models.BooleanField(default=False, verbose_name='Доступ к оплатам'),
        ),
        migrations.AlterField(
            model_name='user_mon',
            name='avail_balance',
            field=models.BigIntegerField(default=0, null=True, verbose_name='Сумма оплат'),
        ),
        migrations.AlterField(
            model_name='user_mon',
            name='balance',
            field=models.PositiveBigIntegerField(default=0, null=True, verbose_name='Баланс'),
        ),
        migrations.AlterField(
            model_name='user_mon',
            name='date_reg',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата  регистрации'),
        ),
        migrations.AlterField(
            model_name='user_mon',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Доступ к авторизации'),
        ),
        migrations.AlterField(
            model_name='user_mon',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='Права на админа'),
        ),
        migrations.AlterField(
            model_name='user_mon',
            name='login',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='логин'),
        ),
        migrations.AlterField(
            model_name='user_mon',
            name='name',
            field=models.CharField(max_length=100, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='user_mon',
            name='password',
            field=models.CharField(max_length=200, null=True, verbose_name='пароль'),
        ),
        migrations.AlterField(
            model_name='user_mon',
            name='region',
            field=models.CharField(choices=[('Чуйская', 'Чуйская'), ('Иссык-кульская', 'Иссык-кульская'), ('Нарынская', 'Нарынская'), ('Джалал-Абадская', 'Джалал-Абадская'), ('Баткенская', 'Баткенская'), ('Ошская', 'Ошская'), ('Таласская', 'Таласская')], default='Чуйская', max_length=100, verbose_name='Регион'),
        ),
        migrations.AlterField(
            model_name='user_mon',
            name='surname',
            field=models.CharField(max_length=100, null=True, verbose_name='Фамилия'),
        ),
    ]
