# Generated by Django 3.1.7 on 2023-04-10 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localpay', '0005_auto_20230410_0856'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='mont_avail_balance',
            field=models.BigIntegerField(default=0, null=True, verbose_name='Сумма оплат'),
        ),
        migrations.AddField(
            model_name='comment',
            name='mont_balance',
            field=models.PositiveBigIntegerField(default=0, null=True, verbose_name='Баланс'),
        ),
    ]
