# Generated by Django 3.1.7 on 2023-04-10 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localpay', '0006_auto_20230410_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_mon',
            name='balance',
            field=models.PositiveBigIntegerField(default=0, editable=False, null=True, verbose_name='Баланс'),
        ),
    ]
