# Generated by Django 3.1.7 on 2023-04-10 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localpay', '0009_auto_20230410_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_mon',
            name='comment',
            field=models.CharField(max_length=10000, null=True),
        ),
    ]
