# Generated by Django 3.1.7 on 2023-04-10 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localpay', '0010_user_mon_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='new_avail_balance',
            field=models.BigIntegerField(default=0, null=True, verbose_name='Списание'),
        ),
        migrations.AddField(
            model_name='comment',
            name='new_balance',
            field=models.BigIntegerField(default=0, null=True, verbose_name='Пополненная сумма'),
        ),
        migrations.AddField(
            model_name='comment',
            name='old_avail_balance',
            field=models.BigIntegerField(default=0, null=True, verbose_name='До списания'),
        ),
        migrations.AddField(
            model_name='comment',
            name='old_balance',
            field=models.BigIntegerField(default=0, null=True, verbose_name='До пололнения '),
        ),
    ]
