# Generated by Django 3.1.7 on 2023-04-11 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localpay', '0013_auto_20230410_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='pays',
            name='annulment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pays',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='pays',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
