# Generated by Django 3.1.7 on 2023-04-12 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localpay', '0014_auto_20230411_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='type_pay',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(null=True),
        ),
    ]
