# Generated by Django 3.1.7 on 2023-04-12 05:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('localpay', '0015_auto_20230412_0859'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Операции платежей', 'verbose_name_plural': 'Операции платежей'},
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(null=True, verbose_name='Комментарии'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='type_pay',
            field=models.CharField(max_length=30, null=True, verbose_name='Тип платежа'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='Монтажник'),
        ),
        migrations.AlterField(
            model_name='pays',
            name='annulment',
            field=models.BooleanField(default=False, verbose_name='Аннулирование'),
        ),
        migrations.AlterField(
            model_name='pays',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Комментарии'),
        ),
    ]
